/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Win10
 */
public class CadastroMedico extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMedico
     */
    public CadastroMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblai = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCrm = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtLogradouro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtEspecialidade = new javax.swing.JTextField();
        txtDataNas = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        ckSenha = new javax.swing.JCheckBox();
        btnSair7 = new javax.swing.JButton();
        aa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Nome Completo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 140, 120, 18);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Idade: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 170, 60, 18);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Data de Nascimento: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 140, 140, 18);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Cidade: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 260, 70, 18);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Bairro: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 230, 70, 18);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("RG:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 200, 50, 18);

        lblai.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblai.setText("UF: ");
        getContentPane().add(lblai);
        lblai.setBounds(460, 260, 40, 18);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Logradouro: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 230, 100, 18);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("CEP: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 290, 60, 18);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("CPF: ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 200, 60, 18);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("Contato: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(140, 170, 80, 18);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel13.setText("CRM: ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(450, 290, 60, 18);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setText("Especialidade: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(110, 320, 110, 18);
        getContentPane().add(txtCrm);
        txtCrm.setBounds(520, 290, 120, 22);
        getContentPane().add(txtNome);
        txtNome.setBounds(220, 140, 120, 22);
        getContentPane().add(txtContato);
        txtContato.setBounds(220, 170, 120, 22);
        getContentPane().add(txtCpf);
        txtCpf.setBounds(220, 200, 120, 22);
        getContentPane().add(txtLogradouro);
        txtLogradouro.setBounds(220, 230, 120, 22);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(220, 260, 120, 22);
        getContentPane().add(txtCep);
        txtCep.setBounds(220, 290, 120, 22);
        getContentPane().add(txtEspecialidade);
        txtEspecialidade.setBounds(220, 320, 120, 22);
        getContentPane().add(txtDataNas);
        txtDataNas.setBounds(520, 140, 120, 22);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(520, 230, 120, 22);
        getContentPane().add(txtEstado);
        txtEstado.setBounds(520, 260, 120, 22);
        getContentPane().add(txtIdade);
        txtIdade.setBounds(520, 170, 120, 22);
        getContentPane().add(txtRg);
        txtRg.setBounds(520, 200, 120, 22);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro Médico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 80, 240, 35);

        btnSalvar.setBackground(new java.awt.Color(0, 0, 102));
        btnSalvar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(360, 400, 90, 30);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setText("Email: ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(140, 350, 70, 18);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(210, 350, 130, 30);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setText("Senha: ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(450, 330, 60, 18);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(510, 330, 140, 30);

        ckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(ckSenha);
        ckSenha.setBounds(660, 330, 85, 40);

        btnSair7.setBackground(new java.awt.Color(255, 0, 0));
        btnSair7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSair7.setForeground(new java.awt.Color(255, 255, 255));
        btnSair7.setText("Sair X");
        btnSair7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair7);
        btnSair7.setBounds(660, 20, 70, 25);

        aa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/FundoBom.jpeg"))); // NOI18N
        getContentPane().add(aa);
        aa.setBounds(0, 10, 750, 430);

        setSize(new java.awt.Dimension(753, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvarNoBancoDeDados();
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void ckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSenhaActionPerformed
        // TODO add your handling code here:
         if (ckSenha.isSelected()) {
            txtSenha.setEchoChar((char) 0); // Mostrar texto claro
        } else {
            txtSenha.setEchoChar('*'); // Ocultar senha
        }
    }//GEN-LAST:event_ckSenhaActionPerformed

    private void btnSair7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair7ActionPerformed
        // TODO add your handling code here:
        CadastroEscolha telaCadastroEscolha = new CadastroEscolha();
        dispose();
        telaCadastroEscolha.setVisible(true);
    }//GEN-LAST:event_btnSair7ActionPerformed
    
    public void salvarNoBancoDeDados() {
        String nome = txtNome.getText();
        int idade = Integer.parseInt(txtIdade.getText());
        String cpf = txtCpf.getText();
        String rg = txtRg.getText();
        String crm = txtCrm.getText();
        String especialidade = txtEspecialidade.getText();
        String logradouro = txtLogradouro.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String cep = txtCep.getText();
        String telefone = txtContato.getText();
        String email = txtEmail.getText();
          String senha = txtSenha.getText();

        // Conexão com o banco de dados
        String url = "jdbc:mysql://localhost:3306/PrintClinical";
        String usuario = "root";
        String Usenha = "admin123";

        try (Connection conexao = DriverManager.getConnection(url, usuario, Usenha)) {
            String sql = "INSERT INTO medico (nome, idade, cpf, rg, crm, especialidade, logradouro, bairro, cidade, estado, cep, telefone, email, senha) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement declaracao = conexao.prepareStatement(sql);
            declaracao.setString(1, nome);
            declaracao.setInt(2, idade);
            declaracao.setString(3, cpf);
            declaracao.setString(4, rg);
            declaracao.setString(5, crm);
            declaracao.setString(6, especialidade);
            declaracao.setString(7, logradouro);
            declaracao.setString(8, bairro);
            declaracao.setString(9, cidade);
            declaracao.setString(10, estado);
            declaracao.setString(11, cep);
            declaracao.setString(12, telefone);
            declaracao.setString(13, email);
            declaracao.setString(14, senha);
            declaracao.executeUpdate();
            System.out.println("Médico cadastrado com sucesso!");
            JOptionPane.showMessageDialog(this, "Os dados foram salvos com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            System.out.println("Erro ao cadastrar médico: " + e.getMessage());
        }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aa;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSair1;
    private javax.swing.JButton btnSair2;
    private javax.swing.JButton btnSair3;
    private javax.swing.JButton btnSair4;
    private javax.swing.JButton btnSair5;
    private javax.swing.JButton btnSair6;
    private javax.swing.JButton btnSair7;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox ckSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblai;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCrm;
    private javax.swing.JTextField txtDataNas;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEspecialidade;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRg;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
