/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Telas;
import javax.swing.*;

/**
 *
 * @author Win10
 */
public class CadastroEscolha extends javax.swing.JFrame {

    /** Creates new form CadastroEscolha */
    public CadastroEscolha() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnTipoUser = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        rbtnMedico = new javax.swing.JRadioButton();
        rbtnPaciente = new javax.swing.JRadioButton();
        btnAvacar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Qual tipo de usuário será cadastrado?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 130, 300, 21);

        rbtnTipoUser.add(rbtnMedico);
        rbtnMedico.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        rbtnMedico.setText("Médico");
        rbtnMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnMedico);
        rbtnMedico.setBounds(220, 210, 70, 23);

        rbtnTipoUser.add(rbtnPaciente);
        rbtnPaciente.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        rbtnPaciente.setText("Paciente");
        rbtnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnPaciente);
        rbtnPaciente.setBounds(350, 210, 98, 21);

        btnAvacar.setBackground(new java.awt.Color(0, 0, 102));
        btnAvacar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnAvacar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvacar.setText("Avançar");
        btnAvacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvacarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvacar);
        btnAvacar.setBounds(260, 313, 120, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/fundo branco.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 490, 320);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/WhatsApp Image 2024-06-07 at 21.29.00.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 480);

        setSize(new java.awt.Dimension(682, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMedicoActionPerformed

    private void rbtnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnPacienteActionPerformed

    private void btnAvacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvacarActionPerformed
        // TODO add your handling code here:
        
        if (rbtnMedico.isSelected()) {
                    CadastroMedico telaCadastroMedico = new CadastroMedico();
                    dispose(); // Fecha a tela atual
                    telaCadastroMedico.setVisible(true); // Abre a tela de cadastro médico
                } else if (rbtnPaciente.isSelected()) {
                    CadastroPaciente telaCadastroPaciente = new CadastroPaciente();
                    dispose(); // Fecha a tela atual
                    telaCadastroPaciente.setVisible(true); // Abre a tela de cadastro paciente
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor, selecione uma opção.");
                }
        
    }//GEN-LAST:event_btnAvacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEscolha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvacar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbtnMedico;
    private javax.swing.JRadioButton rbtnPaciente;
    private javax.swing.ButtonGroup rbtnTipoUser;
    // End of variables declaration//GEN-END:variables

}
