/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Win10
 */
public class CadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPaciente
     */
    public CadastroPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void salvarNoBancoDeDados() {
        String nome = txtNome.getText();
        String dataNascimento = txtDataNas.getText();
        int idade = Integer.parseInt(txtIdade.getText());
        String cpf = txtCpf.getText();
        String rg = txtRg.getText();
        String convenio = txtConvenio.getText();
        String numeroConvenio = txtNumeroConvenio.getText();
        String comorbidades = txtAlergia.getText();
        String logradouro = txtLogradouro.getText();
        String bairro = txtBairro.getText();
        String cidade = txtCidade.getText();
        String estado = txtEstado.getText();
        String cep = txtCep.getText();
        String telefone = txtContato.getText();
         String email = txtEmail.getText();
          String senha = txtSenha.getText();

        // Conexão com o banco de dados
        String url = "jdbc:mysql://localhost:3306/PrintClinical";
        String usuario = "root";
        String Usenha = "admin123";

        try (Connection conexao = DriverManager.getConnection(url, usuario, Usenha)) {
            String sql = "INSERT INTO paciente (nome, idade, cpf, rg, convenio, numero_convenio, comorbidades, logradouro, bairro, cidade, estado, cep, telefone, dataNascimento, email, senha) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,? ,?)";
            PreparedStatement declaracao = conexao.prepareStatement(sql);
            declaracao.setString(1, nome);
            declaracao.setInt(2, idade);
            declaracao.setString(3, cpf);
            declaracao.setString(4, rg);
            declaracao.setString(5, convenio);
            declaracao.setString(6, numeroConvenio);
            declaracao.setString(7, comorbidades);
            declaracao.setString(8, logradouro);
            declaracao.setString(9, bairro);
            declaracao.setString(10, cidade);
            declaracao.setString(11, estado);
            declaracao.setString(12, cep);
            declaracao.setString(13, telefone);
            declaracao.setString(14, dataNascimento);
            declaracao.setString(15, email);
            declaracao.setString(16, senha);
            declaracao.executeUpdate();
            System.out.println("Paciente cadastrado com sucesso!");
            JOptionPane.showMessageDialog(this, "Os dados foram salvos com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            System.out.println("Erro ao cadastrar paciente: " + e.getMessage());
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblai = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNumeroConvenio = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtLogradouro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtConvenio = new javax.swing.JTextField();
        txtDataNas = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAlergia = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        ckSenha = new javax.swing.JCheckBox();
        btnSair7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Nome Completo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 110, 120, 18);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Idade: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 140, 60, 18);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Data de Nascimento: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 110, 140, 18);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Cidade: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 230, 70, 18);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Bairro: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 200, 70, 18);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("RG:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 170, 50, 18);

        lblai.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblai.setText("UF: ");
        getContentPane().add(lblai);
        lblai.setBounds(460, 230, 30, 18);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Logradouro: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 200, 100, 18);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("CEP: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 260, 60, 18);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("CPF: ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(170, 170, 60, 18);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("Contato: ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(150, 140, 80, 18);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel13.setText("Nº Convênio: ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(410, 260, 100, 18);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setText("Email: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(140, 320, 70, 18);
        getContentPane().add(txtNumeroConvenio);
        txtNumeroConvenio.setBounds(510, 260, 120, 22);
        getContentPane().add(txtNome);
        txtNome.setBounds(230, 110, 120, 22);
        getContentPane().add(txtContato);
        txtContato.setBounds(230, 140, 120, 22);
        getContentPane().add(txtCpf);
        txtCpf.setBounds(230, 170, 120, 22);
        getContentPane().add(txtLogradouro);
        txtLogradouro.setBounds(230, 200, 120, 22);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(230, 230, 120, 22);
        getContentPane().add(txtCep);
        txtCep.setBounds(230, 260, 120, 22);
        getContentPane().add(txtConvenio);
        txtConvenio.setBounds(230, 290, 120, 20);
        getContentPane().add(txtDataNas);
        txtDataNas.setBounds(510, 110, 120, 22);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(510, 200, 120, 22);
        getContentPane().add(txtEstado);
        txtEstado.setBounds(510, 230, 120, 22);
        getContentPane().add(txtIdade);
        txtIdade.setBounds(510, 140, 120, 22);
        getContentPane().add(txtRg);
        txtRg.setBounds(510, 170, 120, 22);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        jLabel1.setText("Alergia ou Comorbidade: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 290, 143, 15);

        txtAlergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlergiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlergia);
        txtAlergia.setBounds(510, 290, 130, 40);

        btnSalvar.setBackground(new java.awt.Color(0, 0, 102));
        btnSalvar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(330, 390, 90, 30);

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel15.setText("Cadastro Paciente");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(240, 60, 270, 35);

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setText("Convênio: ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(140, 290, 110, 18);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(230, 320, 130, 30);

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setText("Senha: ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(450, 340, 60, 18);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(510, 330, 140, 30);

        ckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(ckSenha);
        ckSenha.setBounds(650, 340, 19, 19);

        btnSair7.setBackground(new java.awt.Color(255, 0, 0));
        btnSair7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSair7.setForeground(new java.awt.Color(255, 255, 255));
        btnSair7.setText("Sair X");
        btnSair7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair7);
        btnSair7.setBounds(660, 10, 70, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/FundoBom.jpeg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, -30, 750, 480);

        setSize(new java.awt.Dimension(750, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlergiaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvarNoBancoDeDados();
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void ckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSenhaActionPerformed
        // TODO add your handling code here:
         if (ckSenha.isSelected()) {
            txtSenha.setEchoChar((char) 0); // Mostrar texto claro
        } else {
            txtSenha.setEchoChar('*'); // Ocultar senha
        }
    }//GEN-LAST:event_ckSenhaActionPerformed

    private void btnSair7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair7ActionPerformed
        // TODO add your handling code here:
        CadastroEscolha telaCadastroEscolha = new CadastroEscolha();
        dispose();
        telaCadastroEscolha.setVisible(true);
    }//GEN-LAST:event_btnSair7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair7;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox ckSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblai;
    private javax.swing.JTextField txtAlergia;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtConvenio;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataNas;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumeroConvenio;
    private javax.swing.JTextField txtRg;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
