/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Win10
 */
public class EsqueceuSenha extends javax.swing.JFrame {

    /**
     * Creates new form EsqueceuSenha
     */
    public EsqueceuSenha() {
        initComponents();
    }
    
    public void alterarSenha() {
    String nome = txtNome.getText();
    int idade = Integer.parseInt(txtIdade.getText()); // Convertendo idade para int
    String contato = txtContato.getText();
    String novaSenha = new String(txtNovaSenha.getPassword());
    String confirmarSenha = new String(txtSenhaNova.getPassword());

    // Conectar ao banco de dados
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/PrintClinical", "root", "admin123");

        // Verificar se os dados correspondem a um registro na tabela de médicos
        String consultaMedico = "SELECT * FROM medico WHERE nome = ? AND idade = ? AND telefone = ?";
        PreparedStatement stmtMedico = conn.prepareStatement(consultaMedico);
        stmtMedico.setString(1, nome);
        stmtMedico.setInt(2, idade);
        stmtMedico.setString(3, contato);
        ResultSet rsMedico = stmtMedico.executeQuery();

        if (rsMedico.next()) {
            // Atualizar a senha do médico
            String updateSenhaMedico = "UPDATE medico SET senha = ? WHERE nome = ?";
            PreparedStatement stmtUpdateMedico = conn.prepareStatement(updateSenhaMedico);
            stmtUpdateMedico.setString(1, novaSenha);
            stmtUpdateMedico.setString(2, nome);
            stmtUpdateMedico.executeUpdate();
            JOptionPane.showMessageDialog(this, "Senha atualizada com sucesso para médico.");
            return;
        }

        // Verificar se os dados correspondem a um registro na tabela de pacientes
        String consultaPaciente = "SELECT * FROM paciente WHERE nome = ? AND idade = ? AND telefine = ?";
        PreparedStatement stmtPaciente = conn.prepareStatement(consultaPaciente);
        stmtPaciente.setString(1, nome);
        stmtPaciente.setInt(2, idade);
        stmtPaciente.setString(3, contato);
        ResultSet rsPaciente = stmtPaciente.executeQuery();

        if (rsPaciente.next()) {
            // Atualizar a senha do paciente
            String updateSenhaPaciente = "UPDATE paciente SET senha = ? WHERE nome = ?";
            PreparedStatement stmtUpdatePaciente = conn.prepareStatement(updateSenhaPaciente);
            stmtUpdatePaciente.setString(1, novaSenha);
            stmtUpdatePaciente.setString(2, nome);
            stmtUpdatePaciente.executeUpdate();
            JOptionPane.showMessageDialog(this, "Senha atualizada com sucesso para paciente.");
            return;
        }

        // Se os dados não foram encontrados em nenhuma tabela
        JOptionPane.showMessageDialog(this, "Não foi possível atualizar a senha. Dados não conferem.");
        conn.close(); // Fechar a conexão com o banco de dados
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro, Dados não conferem.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNovaSenha = new javax.swing.JPasswordField();
        txtSenhaNova = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtContato = new javax.swing.JTextField();
        ckSenha = new javax.swing.JCheckBox();
        ckSenha2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Informe seu nome: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 160, 150, 18);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Seu Contato: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 230, 110, 18);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Informe sua Idade: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 200, 140, 18);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Informe a Nova Senha: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 290, 160, 18);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirme a Senha:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 330, 140, 18);
        getContentPane().add(txtNovaSenha);
        txtNovaSenha.setBounds(380, 290, 190, 30);
        getContentPane().add(txtSenhaNova);
        txtSenhaNova.setBounds(380, 330, 190, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Alterar Senha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 380, 130, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(380, 160, 190, 30);
        getContentPane().add(txtIdade);
        txtIdade.setBounds(380, 200, 190, 30);
        getContentPane().add(txtContato);
        txtContato.setBounds(380, 230, 190, 30);

        ckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(ckSenha);
        ckSenha.setBounds(580, 290, 19, 19);

        ckSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSenha2ActionPerformed(evt);
            }
        });
        getContentPane().add(ckSenha2);
        ckSenha2.setBounds(580, 330, 30, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/fundoAzul.jpeg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 280, 650, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/Esqueceu Senha.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 840, 490);

        setSize(new java.awt.Dimension(857, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        alterarSenha();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSenhaActionPerformed
        // TODO add your handling code here:
        if (ckSenha.isSelected()) {
                    txtNovaSenha.setEchoChar((char) 0); // Mostrar texto claro
        } else {
            txtNovaSenha.setEchoChar('*'); // Ocultar senha
        }
    }//GEN-LAST:event_ckSenhaActionPerformed

    private void ckSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSenha2ActionPerformed
        // TODO add your handling code here:
        if (ckSenha2.isSelected()) {
            txtSenhaNova.setEchoChar((char) 0); // Mostrar texto claro
        } else {
            txtSenhaNova.setEchoChar('*'); // Ocultar senha
        }
    }//GEN-LAST:event_ckSenha2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EsqueceuSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckSenha;
    private javax.swing.JCheckBox ckSenha2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtNovaSenha;
    private javax.swing.JPasswordField txtSenhaNova;
    // End of variables declaration//GEN-END:variables
}
