/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Win10
 */
public class Exames extends javax.swing.JFrame {

    /**
     * Creates new form Exames
     */
    public Exames() {
        initComponents();
    }
     public void setNomePaciente(String nome) {
        txtNomePaciente.setText(nome);
    }
    
    public void setDataConsulta(String data) {
        txtData.setText(data);
    }
    public void setNomeMedico(String nomeMedico) {
        lblMedico.setText(nomeMedico);
    }
    public void setEspecialidade(String especialidade) {
        lblEspecialidade.setText(especialidade);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtExames = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMedico = new javax.swing.JLabel();
        lblEspecialidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair X");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(780, 20, 70, 25);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Nome do Paciente: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 110, 140, 18);

        txtNomePaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNomePaciente.setText("...");
        getContentPane().add(txtNomePaciente);
        txtNomePaciente.setBounds(240, 110, 230, 20);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Data: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 110, 50, 18);

        txtData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtData.setText("...");
        getContentPane().add(txtData);
        txtData.setBounds(540, 110, 210, 20);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Área Exames");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 150, 130, 20);

        txtExames.setColumns(20);
        txtExames.setRows(5);
        jScrollPane1.setViewportView(txtExames);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 180, 730, 240);

        btnSalvar.setBackground(new java.awt.Color(0, 0, 102));
        btnSalvar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(680, 150, 110, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/Exames.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 858, 472);

        lblMedico.setText("jLabel3");
        getContentPane().add(lblMedico);
        lblMedico.setBounds(400, 100, 37, 16);

        lblEspecialidade.setText("jLabel3");
        getContentPane().add(lblEspecialidade);
        lblEspecialidade.setBounds(390, 70, 37, 16);

        setSize(new java.awt.Dimension(902, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        ParteMedica telaParteMedica = new ParteMedica();
        dispose();
        telaParteMedica.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed
    

    // Método para salvar o texto do JTextArea (opcional)
        
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
       
        

        // Exibir a janela da classe Prescrever
        
        String exames = txtExames.getText();

        // Conectar ao banco de dados
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/PrintClinical", "root", "admin123")) {

            // Preparar a declaração SQL para inserir os dados na tabela prescricao
            String sql = "INSERT INTO exames (nome_paciente, data_consulta, nome_medico, especialidade, exames) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1, txtNomePaciente.getText());
            statement.setString(2, txtData.getText());
            statement.setString(3, lblMedico.getText());
            statement.setString(4, lblEspecialidade.getText());
            statement.setString(5, exames);

            // Executar a declaração SQL
            int rowsInserted = statement.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Exames salva com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar Exames.");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel txtData;
    private javax.swing.JTextArea txtExames;
    private javax.swing.JLabel txtNomePaciente;
    // End of variables declaration//GEN-END:variables
}
