/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Win10
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnUsuario = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        btnEsqueceuSenha = new javax.swing.JButton();
        rbtnMedico = new javax.swing.JRadioButton();
        rbtnPaciente = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        ckSenha = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-mail");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 250, 90, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Você é: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 370, 60, 18);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(270, 240, 250, 40);

        btnEntrar.setBackground(new java.awt.Color(0, 0, 102));
        btnEntrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(340, 440, 100, 40);

        btnEsqueceuSenha.setForeground(new java.awt.Color(51, 51, 255));
        btnEsqueceuSenha.setText("Esqueceu Senha?");
        btnEsqueceuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsqueceuSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsqueceuSenha);
        btnEsqueceuSenha.setBounds(310, 410, 170, 23);

        rbtnUsuario.add(rbtnMedico);
        rbtnMedico.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        rbtnMedico.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMedico.setText("Médico");
        getContentPane().add(rbtnMedico);
        rbtnMedico.setBounds(300, 370, 98, 21);

        rbtnUsuario.add(rbtnPaciente);
        rbtnPaciente.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        rbtnPaciente.setForeground(new java.awt.Color(255, 255, 255));
        rbtnPaciente.setText("Paciente");
        getContentPane().add(rbtnPaciente);
        rbtnPaciente.setBounds(390, 370, 81, 23);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 320, 90, 18);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(270, 320, 250, 40);

        ckSenha.setMaximumSize(new java.awt.Dimension(50, 50));
        ckSenha.setMinimumSize(new java.awt.Dimension(50, 50));
        ckSenha.setPreferredSize(new java.awt.Dimension(50, 50));
        ckSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(ckSenha);
        ckSenha.setBounds(530, 320, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/Login.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 0, 800, 660);

        setSize(new java.awt.Dimension(798, 627));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
     String email = txtEmail.getText();
     String senha = txtSenha.getText();

     // Conexão com o banco de dados
     String url = "jdbc:mysql://localhost:3306/PrintClinical";
     String usuarioBD = "root";
     String senhaBD = "admin123";

     try (Connection conexao = DriverManager.getConnection(url, usuarioBD, senhaBD)) {
         // Verifica se o e-mail está na tabela de administradores
         String sqlAdmin = "SELECT * FROM admin WHERE email = ?";
         PreparedStatement declaracaoAdmin = conexao.prepareStatement(sqlAdmin);
         declaracaoAdmin.setString(1, email);
         ResultSet resultadoAdmin = declaracaoAdmin.executeQuery();

         // Se o e-mail estiver na tabela de administradores
         if (resultadoAdmin.next()) {
             JOptionPane.showMessageDialog(this, "Bem-vindo(a) Admin", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
             // Redirecionar para a tela de escolha de cadastro
             CadastroEscolha telaCadastroEscolha = new CadastroEscolha();
             dispose(); // Fecha a tela atual
             telaCadastroEscolha.setVisible(true);
             return;
         }

         // Se o e-mail não estiver na tabela de administradores, verifica médicos e pacientes
         String sql = "";
         if (rbtnMedico.isSelected()) {
             sql = "SELECT nome FROM medico WHERE email = ? AND senha = ?";
         } else if (rbtnPaciente.isSelected()) {
             sql = "SELECT nome FROM paciente WHERE email = ? AND senha = ?";
         }

         PreparedStatement declaracao = conexao.prepareStatement(sql);
         declaracao.setString(1, email);
         declaracao.setString(2, senha);
         ResultSet resultado = declaracao.executeQuery();

         if (resultado.next()) {
             String nome = resultado.getString("nome");
             String mensagem = "";

             if (rbtnMedico.isSelected()) {
                 mensagem = "Bem-vindo(a) Dr(a). " + nome;
                 // Redirecionar para a parte médica
                 ParteMedica telaParteMedica = new ParteMedica();
                 telaParteMedica.setNomeMedico(nome);
                 dispose(); // Fecha a tela atual
                 telaParteMedica.setVisible(true);
             } else if (rbtnPaciente.isSelected()) {
                 mensagem = "Bem-vindo(a) Senhor(a) " + nome;
                 String nomePaciente = nome;
                 // Redirecionar para a tela de marcação de consultas
                 MarcarConsultas telaMarcarConsultas = new MarcarConsultas();
                 telaMarcarConsultas.setNomePaciente(nome);
                 dispose(); // Fecha a tela atual
                 telaMarcarConsultas.setVisible(true);
             }

             JOptionPane.showMessageDialog(this, mensagem, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
         } else {
             JOptionPane.showMessageDialog(this, "E-mail ou senha incorretos!", "Erro", JOptionPane.ERROR_MESSAGE);
         }
     } catch (SQLException e) {
         System.out.println("Erro ao conectar no banco de dados: " + e.getMessage());
         JOptionPane.showMessageDialog(this, "Selecione quem você é", "Erro", JOptionPane.ERROR_MESSAGE);
     } 

    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEsqueceuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsqueceuSenhaActionPerformed
        // TODO add your handling code here:
        EsqueceuSenha telaEsqueceuSenha = new EsqueceuSenha();
        dispose();
        telaEsqueceuSenha.setVisible(true);
    }//GEN-LAST:event_btnEsqueceuSenhaActionPerformed

    private void ckSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSenhaActionPerformed
        // TODO add your handling code here:
        if (ckSenha.isSelected()) {
            txtSenha.setEchoChar((char) 0); // Mostrar texto claro
        } else {
            txtSenha.setEchoChar('*'); // Ocultar senha
        }
    }//GEN-LAST:event_ckSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnEsqueceuSenha;
    private javax.swing.JCheckBox ckSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbtnMedico;
    private javax.swing.JRadioButton rbtnPaciente;
    private javax.swing.ButtonGroup rbtnUsuario;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
