/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Win10
 */
public class ParteMedica extends javax.swing.JFrame {
    
     private String nomeMedico;
      private String especialidadeMedico;
   
    public void setNomeMedico(String nomeMedico) {
        this.nomeMedico = nomeMedico;
    }
    public void setEspecialidadeMedico(String especialidadeMedico) {
        this.especialidadeMedico = especialidadeMedico;
    }

    /**
     * Creates new form ParteMedica
     */
    public ParteMedica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnHorarios = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        rbtnNove = new javax.swing.JRadioButton();
        rbtnDoze = new javax.swing.JRadioButton();
        rbtnTreze = new javax.swing.JRadioButton();
        rbtnDez = new javax.swing.JRadioButton();
        rbtnOnze = new javax.swing.JRadioButton();
        rbtnCatorze = new javax.swing.JRadioButton();
        rbtnQuinze = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomePaciente = new javax.swing.JLabel();
        txtNomeMedico = new javax.swing.JLabel();
        txtEspecialidade = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        txtHorario = new javax.swing.JLabel();
        btnProcurar = new javax.swing.JButton();
        btnPrescricao1 = new javax.swing.JButton();
        txtDiaCerto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Selecione um Horário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 140, 150, 18);

        rbtnHorarios.add(rbtnNove);
        rbtnNove.setText("09:00");
        rbtnNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNoveActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnNove);
        rbtnNove.setBounds(50, 170, 70, 21);

        rbtnHorarios.add(rbtnDoze);
        rbtnDoze.setText("12:00");
        getContentPane().add(rbtnDoze);
        rbtnDoze.setBounds(50, 190, 60, 21);

        rbtnHorarios.add(rbtnTreze);
        rbtnTreze.setText("13:00");
        getContentPane().add(rbtnTreze);
        rbtnTreze.setBounds(110, 190, 60, 21);

        rbtnHorarios.add(rbtnDez);
        rbtnDez.setText("10:00");
        getContentPane().add(rbtnDez);
        rbtnDez.setBounds(110, 170, 60, 21);

        rbtnHorarios.add(rbtnOnze);
        rbtnOnze.setText("11:00");
        getContentPane().add(rbtnOnze);
        rbtnOnze.setBounds(170, 170, 60, 21);

        rbtnHorarios.add(rbtnCatorze);
        rbtnCatorze.setText("14:00");
        getContentPane().add(rbtnCatorze);
        rbtnCatorze.setBounds(170, 190, 60, 21);

        rbtnHorarios.add(rbtnQuinze);
        rbtnQuinze.setText("15:00");
        getContentPane().add(rbtnQuinze);
        rbtnQuinze.setBounds(110, 210, 60, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Nome do Médico: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 160, 130, 20);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Data: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(540, 200, 50, 20);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Especialidade: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 180, 110, 20);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Horário: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 220, 60, 20);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Nome do Paciente: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 140, 140, 20);

        txtNomePaciente.setText("...");
        getContentPane().add(txtNomePaciente);
        txtNomePaciente.setBounds(590, 140, 230, 20);

        txtNomeMedico.setText("...");
        getContentPane().add(txtNomeMedico);
        txtNomeMedico.setBounds(590, 160, 230, 20);

        txtEspecialidade.setText("...");
        getContentPane().add(txtEspecialidade);
        txtEspecialidade.setBounds(590, 180, 230, 20);

        txtData.setText("...");
        getContentPane().add(txtData);
        txtData.setBounds(590, 200, 240, 20);

        txtHorario.setText("...");
        getContentPane().add(txtHorario);
        txtHorario.setBounds(590, 220, 230, 20);

        btnProcurar.setBackground(new java.awt.Color(0, 0, 102));
        btnProcurar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnProcurar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcurar.setText("Procurar Consultas");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcurar);
        btnProcurar.setBounds(240, 200, 170, 25);

        btnPrescricao1.setBackground(new java.awt.Color(0, 0, 102));
        btnPrescricao1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnPrescricao1.setForeground(new java.awt.Color(255, 255, 255));
        btnPrescricao1.setText("Iniciar Prescrição");
        btnPrescricao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescricao1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrescricao1);
        btnPrescricao1.setBounds(350, 370, 170, 25);

        txtDiaCerto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiaCerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaCertoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiaCerto);
        txtDiaCerto.setBounds(240, 160, 50, 22);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 140, 21, 18);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mês");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 140, 26, 18);

        txtMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMes);
        txtMes.setBounds(300, 160, 50, 22);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ano");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(370, 140, 25, 18);

        txtAno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtAno);
        txtAno.setBounds(360, 160, 50, 22);

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair X");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(760, 20, 70, 25);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/divisoria.jpeg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 130, 30, 140);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TelasImgs/ParteMedica.jpeg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 860, 500);

        setSize(new java.awt.Dimension(886, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnNoveActionPerformed

    private void btnPrescricao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescricao1ActionPerformed
        // TODO add your handling code here:
        // Criar uma instância da classe Prescrever
        Prescrever prescreverFrame = new Prescrever();

        // Definir o nome do paciente e a data da consulta na instância da classe Prescrever
        prescreverFrame.setNomePaciente(txtNomePaciente.getText());
        prescreverFrame.setDataConsulta(txtData.getText());
        prescreverFrame.setNomeMedico(txtNomeMedico.getText());
        prescreverFrame.setEspecialidade(txtEspecialidade.getText());

        // Exibir a janela da classe Prescrever
        prescreverFrame.setVisible(true);
    }//GEN-LAST:event_btnPrescricao1ActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        // TODO add your handling code here:
        // Capturar a data e o horário selecionados
        String dia = txtDiaCerto.getText();
        String mes = txtMes.getText();
        String ano = txtAno.getText();
        String dataSelecionada = dia + "/" + mes + "/" + ano;

        String horarioSelecionado = "";
        if (rbtnNove.isSelected()) {
            horarioSelecionado = "09:00";
        } else if (rbtnDez.isSelected()) {
            horarioSelecionado = "10:00";
        } else if (rbtnOnze.isSelected()) {
            horarioSelecionado = "11:00";
        } else if (rbtnDoze.isSelected()) {
            horarioSelecionado = "12:00";
        } else if (rbtnTreze.isSelected()) {
            horarioSelecionado = "13:00";
        } else if (rbtnCatorze.isSelected()) {
            horarioSelecionado = "14:00";
        } else if (rbtnQuinze.isSelected()) {
            horarioSelecionado = "15:00";
        }

        // Passo 4: Conectar ao banco de dados e buscar os dados da consulta
        try {
            // Conectar ao banco de dados
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/PrintClinical", "root", "admin123");

            // Preparar a declaração SQL para buscar os dados da consulta
            String sqlConsulta = "SELECT nome_paciente, nome_medico, especialidade_escolhida, data, horario FROM consultas WHERE data = ? AND horario = ?";
            PreparedStatement statementConsulta = conn.prepareStatement(sqlConsulta);
            statementConsulta.setString(1, dataSelecionada);
            statementConsulta.setString(2, horarioSelecionado);

            // Executar a consulta
            ResultSet rsConsulta = statementConsulta.executeQuery();

            // Verificar se há resultados
            if (!rsConsulta.next()) {
                System.out.println("Nenhuma consulta encontrada para a data e horário selecionados.");
            } else {
                // Loop para imprimir todos os resultados da consulta
                do {
                    // Obter os dados da consulta
                    String nomePaciente = rsConsulta.getString("nome_paciente");
                    String nomeMedico = rsConsulta.getString("nome_medico");
                    String especialidade = rsConsulta.getString("especialidade_escolhida");
                    String dataConsulta = rsConsulta.getString("data");
                    String horarioConsulta = rsConsulta.getString("horario");
                    
                    txtNomePaciente.setText(nomePaciente);
                    txtNomeMedico.setText(nomeMedico);
                    txtEspecialidade.setText(especialidade);
                    txtData.setText(dataConsulta);
                    txtHorario.setText(horarioConsulta);

                } while (rsConsulta.next());
            }

            // Fechar a conexão com o banco de dados
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao buscar consulta. Por favor, tente novamente mais tarde.");
        }

        
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void txtDiaCertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaCertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaCertoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        Login telaLogin = new Login();
        dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed
    
   
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParteMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParteMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParteMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParteMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParteMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrescricao1;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtnCatorze;
    private javax.swing.JRadioButton rbtnDez;
    private javax.swing.JRadioButton rbtnDoze;
    private javax.swing.ButtonGroup rbtnHorarios;
    private javax.swing.JRadioButton rbtnNove;
    private javax.swing.JRadioButton rbtnOnze;
    private javax.swing.JRadioButton rbtnQuinze;
    private javax.swing.JRadioButton rbtnTreze;
    private javax.swing.JTextField txtAno;
    private javax.swing.JLabel txtData;
    private javax.swing.JTextField txtDiaCerto;
    private javax.swing.JLabel txtEspecialidade;
    private javax.swing.JLabel txtHorario;
    private javax.swing.JTextField txtMes;
    private javax.swing.JLabel txtNomeMedico;
    private javax.swing.JLabel txtNomePaciente;
    // End of variables declaration//GEN-END:variables
}
